# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

project 'BikeRide/BikeRide.xcodeproj'

target 'BikeRide' do
  platform :ios, '14.5'
  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'
#  pod 'CoreGPX'
#  pod 'Mapbox-iOS-SDK', '~> 6.3.0'
end

target 'BikeRide WatchKit App' do
  platform :watchos, '7.4'
end

